language: generic

before_install:
    # LaTeX minted
    - sudo apt-get install python-pygments
    # Haskell stack
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - source .texlive/texlive_install.sh

cache:
  directories:
      - "/tmp/texlive"
      - "$HOME/.texlive"
      - "$HOME/.stack"

script:
    - echo "Build Haskell code"
    - stack build
    - echo "Build LaTeX code"
    - mkdir build
    - cd build
    - travis_wait 3 xelatex -shell-escape ../app/Main.lhs
    - travis_wait 3 xelatex -shell-escape ../app/Main.lhs
    - cd ..

deploy:
  provider: releases
  api_key:
    secure: QZ39IaYnYHU7Pv4eewnenuoksncx5DXnVk/dLSD5mgNiO/KzmO2r5Ovgq2nAOH5W0GaheuAs7QCyEvtJIFRjvNU+vWVPg0Xqh9wgqP6R8QUsIzoeBIuh/1fntZh7AElPVbhQnZpqt70nu5057haMORviG2DuunrkryhKiEfpAh8t5mYiqbdMTCL6E5TNlhPykTRWXT4QblggPpOHd+Owc11rDZmKvQ/HTlees6Wh+2d6dKHH1ecFt7rZzV6uP6000A3xlDJ0bAhV26HxBEu5av8oxVwlfX/Jn9oQMXJ+2exBgjwg2t+VOKfiFQ4LIUY/0G3a2LbXv2f7Tj2QY+vwTeK59RG2F0DMYDSbEvxrkLHlfjsK0iHTshbqAWt/8ERtxmeadzxCZ52R5sMExkayw2YbP5ntLFb5kV1ceZU8b4X8qw8Cjc+ht9ft7AkM8M6yhq9X9bWl5Z41JoxTL9z3Smoui3npG/NyC7xHOB6Lv7w3rJgGG3tNJqUc9YiUbKhGHkb/On5JM3fIGAYfifzwF4E2HmblbRQUwvbHcrVYducHvpWK7jpo4MJLB2s+lDrMhvzvaRI2SNc7YV1M84LEswtSE8l8ec9SzSBUuvcyCPUfISxUv5+KwLs62qP7bRoq8BsYPZ+RTipL30/BtWlIjpdJcvD7cquCB+cS2GmMLEc=
  file:
    - ./build/Main.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
