language: generic

# Dependency of the minted package
before_install:
    - sudo apt-get install python-pygments

install:
    - source .texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/
script:
    - mkdir build
    - cd build
    - travis_wait 3 xelatex -shell-escape ../app/Main.lhs
    # Compile twice to fix possible references
    - travis_wait 3 xelatex -shell-escape ../app/Main.lhs
